### ISSUE TITLE
can't open the link of VGG19

### ISSUE THREAD

**Issue by 395062753** [JunbinWang/Tensorflow-Style-Transfer-with-Adain#1]
hi! I 'm learning AdaIN with your project, but I can't open the model downloading link , Please help me...

**Comment by JunbinWang** [comment]
well, the link is from GoogleDrive, maybe you need a VPN to download it if you are in China

**Comment by JunbinWang** [comment]
BTW, do you need the encoder-vgg model or decoder-vgg model, or both of them?

**Comment by 395062753** [comment]
thanks! I have downloaded the model on the link and run the test.py successfully,   from eridgd's project you said that you would to try the  original vgg19 model, have you tried it?

**Comment by JunbinWang** [comment]
Yes, I think it works. You can try to replace the encoder part with other CNN.
